### ISSUE TITLE
Run failed: ‘can only concatenate str (not “list”) to str’ when using llama-3-sqlcoder-8b model in Chatflow

### ISSUE THREAD

**Issue by ChenZixinn** [langgenius/dify#11553]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When using the llama-3-sqlcoder-8b (Completion) model in **Chatflow**, the following error occurs:

Run failed: can only concatenate str (not "list") to str.

However, the model works correctly in **Chatbot Basic**.

**Environment Details:**

​	•	Model: llama-3-sqlcoder-8b (Completion)

​	•	Hosting Platform: Xorbits Inference

​	•	Error Context: Chatflow usage

**Screenshots:**

​	1.	**Chatflow Run Failure**

<img width="1274" alt="chatflow" src="https://github.com/user-attachments/assets/1eeaee96-5045-4bd7-becb-c6dd1fa2a999">

​	2.	**Chatbot Basic Working Normally**
<img width="1268" alt="chatbot" src="https://github.com/user-attachments/assets/9230f281-0b47-4096-94b2-2e6713f001e2">

**Steps to Reproduce:**

​	1.	Install the llama-3-sqlcoder-8b model on Xorbits Inference.

​	2.	Configure it in **Chatflow**.

​	3.	Execute a request.

​	4.	Observe the error message.

### ✔️ Expected Behavior

The model should run in Chatflow without errors, just as it does in Chatbot Basic.

### ❌ Actual Behavior

Run fail.

**Comment by yihong0618** [comment]
fixed int https://github.com/langgenius/dify/pull/11504
can you try the latest version?

**Comment by ChenZixinn** [comment]
I tried on https://cloud.dify.ai, It's the latest version?

**Comment by crazywoola** [comment]
> I tried on https://cloud.dify.ai, It's the latest version?

No, this just merge yesterday. I think this is not on the Cloud.

**Comment by ChenZixinn** [comment]
ok, I will try. Could you tell me in which merge this bug was fixed?

**Comment by ChenZixinn** [comment]
Thanks. It's working as expected.

**Comment by Ryuukeisyou** [comment]
Hi, I have also encountered the same problem, "can only concatenate str (not "list") to str
", with completion models like Llama_3_2_3B_Instruct_Q8_0 and qwen2_5_7b_instruct_q8_0. 

I tried updating dify to latest version using:
`cd dify/docker`
`docker compose down`
`git pull origin main`
`docker compose pull`
`docker compose up -d`

but the problem still exist. Any help would be appreciated.

**Comment by yihong0618** [comment]
> Hi, I have also encountered the same problem, "can only concatenate str (not "list") to str ", with completion models like Llama_3_2_3B_Instruct_Q8_0 and qwen2_5_7b_instruct_q8_0.
> 
> I tried updating dify to latest version using: `cd dify/docker` `docker compose down` `git pull origin main` `docker compose pull` `docker compose up -d`
> 
> but the problem still exist. This is the dsl I am using. Any help would be appreciated. Thank you! @crazywoola [test_00.zip](https://github.com/user-attachments/files/18122904/test_00.zip)

Thanks, will check it .

**Comment by ChenZixinn** [comment]
It seems like you are using Docker, and I'm not sure if it is up to date.
In my case, I rebuild the API and WORKER image in the latest version.

**Comment by yihong0618** [comment]
> Hi, I have also encountered the same problem, "can only concatenate str (not "list") to str ", with completion models like Llama_3_2_3B_Instruct_Q8_0 and qwen2_5_7b_instruct_q8_0.
> 
> I tried updating dify to latest version using: `cd dify/docker` `docker compose down` `git pull origin main` `docker compose pull` `docker compose up -d`
> 
> but the problem still exist. This is the dsl I am using. Any help would be appreciated. Thank you! @crazywoola [test_00.zip](https://github.com/user-attachments/files/18122904/test_00.zip)

there's no problem in my side using your dsl please use latest code and retry
