### ISSUE TITLE
Uncaught TypeError: a.variable_selector.join is not a function When open a chatflow

### ISSUE THREAD

**Issue by AllenHu2024** [langgenius/dify#18140]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.2.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I create a workflow and modify it , then reopen, it shows "Application error: a client-side exception has occurred while loading nezha-qa.cn-pgcloud.com (see the browser console for more information)." in web browser. 
Shows"Uncaught TypeError: a.variable_selector.join is not a function" in console.
details as below:
4348-77eed836ff068e0f.js:1  Uncaught TypeError: a.variable_selector.join is not a function
    at 4348-77eed836ff068e0f.js:1:1323942
    at 4348-77eed836ff068e0f.js:1:609666
    at Array.filter (<anonymous>)
    at f (4348-77eed836ff068e0f.js:1:609644)
    at 4348-77eed836ff068e0f.js:1:610853
    at Array.map (<anonymous>)
    at C (4348-77eed836ff068e0f.js:1:610841)
    at N (4348-77eed836ff068e0f.js:1:614027)
    at 4348-77eed836ff068e0f.js:1:1475903
    at n (4348-77eed836ff068e0f.js:1:1532820)
    at 4348-77eed836ff068e0f.js:1:636004
    at lS (965d0215-d661dd9fca8e5b15.js:1:39325)
    at ot (965d0215-d661dd9fca8e5b15.js:1:64573)
    at a9 (965d0215-d661dd9fca8e5b15.js:1:63435)
    at a5 (965d0215-d661dd9fca8e5b15.js:1:63052)
    at ov (965d0215-d661dd9fca8e5b15.js:1:79228)
    at ic (965d0215-d661dd9fca8e5b15.js:1:112360)
    at 965d0215-d661dd9fca8e5b15.js:1:112205
    at is (965d0215-d661dd9fca8e5b15.js:1:112213)
    at u9 (965d0215-d661dd9fca8e5b15.js:1:109424)
    at iQ (965d0215-d661dd9fca8e5b15.js:1:130771)
    at iI (965d0215-d661dd9fca8e5b15.js:1:129010)
    at ib (965d0215-d661dd9fca8e5b15.js:1:125930)
    at ig (965d0215-d661dd9fca8e5b15.js:1:123682)
    at u7 (965d0215-d661dd9fca8e5b15.js:1:110614)
    at u9 (965d0215-d661dd9fca8e5b15.js:1:109967)
    at iH (965d0215-d661dd9fca8e5b15.js:1:130650)
    at MessagePort.w (8418-76f95aa25de7d6e2.js:1:26528)
(anonymous) @ 4348-77eed836ff068e0f.js:1
(anonymous) @ 4348-77eed836ff068e0f.js:1
f @ 4348-77eed836ff068e0f.js:1
(anonymous) @ 4348-77eed836ff068e0f.js:1
C @ 4348-77eed836ff068e0f.js:1
N @ 4348-77eed836ff068e0f.js:1
(anonymous) @ 4348-77eed836ff068e0f.js:1
n @ 4348-77eed836ff068e0f.js:1
(anonymous) @ 4348-77eed836ff068e0f.js:1
lS @ 965d0215-d661dd9fca8e5b15.js:1
ot @ 965d0215-d661dd9fca8e5b15.js:1
a9 @ 965d0215-d661dd9fca8e5b15.js:1
a5 @ 965d0215-d661dd9fca8e5b15.js:1
ov @ 965d0215-d661dd9fca8e5b15.js:1
ic @ 965d0215-d661dd9fca8e5b15.js:1
(anonymous) @ 965d0215-d661dd9fca8e5b15.js:1
is @ 965d0215-d661dd9fca8e5b15.js:1
u9 @ 965d0215-d661dd9fca8e5b15.js:1
iQ @ 965d0215-d661dd9fca8e5b15.js:1
iI @ 965d0215-d661dd9fca8e5b15.js:1
ib @ 965d0215-d661dd9fca8e5b15.js:1
ig @ 965d0215-d661dd9fca8e5b15.js:1
u7 @ 965d0215-d661dd9fca8e5b15.js:1
u9 @ 965d0215-d661dd9fca8e5b15.js:1
iH @ 965d0215-d661dd9fca8e5b15.js:1
w @ 8418-76f95aa25de7d6e2.js:1

### ✔️ Expected Behavior

Chatflow runs well.

### ❌ Actual Behavior

it shows "Application error: a client-side exception has occurred while loading nezha-qa.cn-pgcloud.com (see the browser console for more information)." in web browser.

**Comment by AllenHu2024** [comment]
[laundry_insight_bank.yml.txt](https://github.com/us. r-attachments/files/19769897/laundry_insight_bank.yml.txt)   yml as above

**Comment by crazywoola** [comment]
We have fixed it already.

**Comment by AllenHu2024** [comment]
how to fix it in current version by changing DSL? @crazywoola

**Comment by Sakura4036** [comment]
`v1.2.0` +1, Can not reopen my chatflow app! even i try to change it to the **older workflow version** of this app.


![Image](https://github.com/user-attachments/assets/d8084dbd-9025-4a63-ab0a-23b0cd83191e)


@crazywoola  how could we fix this problem?

**Comment by Sakura4036** [comment]
I use the latest version code 7ba3e599d2994a66f345447a08dc12b166807262, still get the same error!

**Comment by wbext** [comment]
I also encountered the same error, and restarting Docker didn't solve the problem. Will this issue be fixed in version 1.3.0?
