### ISSUE TITLE
Traces not streaming

### ISSUE THREAD

**Issue by DavideDelbianco** [langgenius/dify#19909]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After the update to 1.4.0 the traces to Langfuse are no longer being streamed.

### ✔️ Expected Behavior

Should stream traces

### ❌ Actual Behavior

Does not stream

**Comment by DavideDelbianco** [comment]
I've tried to set the credentials for LangFuse again.
What does this even mean ?

![Image](https://github.com/user-attachments/assets/04aaa708-fb08-4768-ae1e-46902274d469)


That's some broken shit introduces because of OpenTelemetry for sure.
Is it possible that every minor version you manage to break everything that was working fine before???

**Comment by DavideDelbianco** [comment]
Adding the credentials after removing the tracing app config returns error 400 even though the credentials are perfectly fine:

![Image](https://github.com/user-attachments/assets/d47aff4b-e815-49c6-ae0b-22fb8c44d200)

**Comment by DavideDelbianco** [comment]
Probably fixed in #19884
@crazywoola when will the patch version be released?

I suppose the execution log data during the existence of this bug is lost....
I should know better and wait a month before upgrading when versions are released...

**Comment by DavideDelbianco** [comment]
I am reopening because looking at the PR probably there are more issues causing this bug other than the one fixed.

When adding a new config, I get an Invalid credentials error even though the credentials are correct.
And creating or updating a Tracing Config hardly has anything to do with already existing configs not being used.

**Comment by DavideDelbianco** [comment]
I confirm that in 1.3.1 worked fine, just tested with a clean install locally.
Furthermore, I have tried to compile latest version and even though the save/update of configuration is fixed... I confirm that metrics are still not being sent to Langfuse.

**Comment by crazywoola** [comment]
> Probably fixed in [#19884](https://github.com/langgenius/dify/pull/19884) [@crazywoola](https://github.com/crazywoola) when will the patch version be released?
> 
> I suppose the execution log data during the existence of this bug is lost.... I should know better and wait a month before upgrading when versions are released...

Will be released this week or later next week eariler.

**Comment by JimHeo** [comment]
same here.

The 400 error in issue https://github.com/langgenius/dify/issues/19867 has been resolved by the derived PRs, but integration with langfuse is still not functioning properly.
