### ISSUE TITLE
The retrieval of the RAGFlow knowledge node returns an incorrect document_id.

### ISSUE THREAD

**Issue by Zpy-ai** [langgenius/dify#22985]
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.5.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Use RAGFlow as an external knowledge base to build a workflow conversation. Access the RAGFlow external knowledge base at the knowledge retrieval node of the workflow and check the values of `document_id` and `document_name` in the knowledge retrieval node. You will find that both values are the same as the value of `document_name`.

### ✔️ Expected Behavior

Using RAGFlow as an external knowledge base, in the knowledge retrieval node of the workflow, the returned `document_id` value and `document_name` value should be different. For example: "document_id": "1bedfe0e-81ce-4f15-af84-f006cedb82e6", "document_name": "learn.docx"

### ❌ Actual Behavior

Use RAGFlow as an external knowledge base. In the knowledge retrieval node of the workflow, both the returned `document_id` value and `document_name` value are "name". For example: "document_id": "learn.docx", "document_name": "learn.docx"

**Comment by baonudesifeizhai** [comment]
<img width="1591" height="557" alt="Image" src="https://github.com/user-attachments/assets/6174afd1-cf39-4e6b-96c9-bcf7cda7d98a" />

<img width="1222" height="316" alt="Image" src="https://github.com/user-attachments/assets/dd28336a-0d98-4c5c-8998-1fe20b0c9fc0" />
looks like they fixed now?

**Comment by Zpy-ai** [comment]
> <img alt="图像" width="1591" height="557" src="https://private-user-images.githubusercontent.com/85092850/471007083-6174afd1-cf39-4e6b-96c9-bcf7cda7d98a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQwNjA1MzAsIm5iZiI6MTc1NDA2MDIzMCwicGF0aCI6Ii84NTA5Mjg1MC80NzEwMDcwODMtNjE3NGFmZDEtY2YzOS00ZTZiLTk2YzktYmNmN2NkYTdkOThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODAxVDE0NTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmN2ZjNjNhYTU1MWM4YWVlYTc3ODUzOTgxNjJlOWUzMGMyZjE0MjkzODMwMDEyYzExYmI4ZWFkZTJhNTQzMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OyZxmVUdmTsfUupMcJVpyw6VYXl3lPp2SlRH7I9t7_E"> <img alt="图像" width="1222" height="316" src="https://private-user-images.githubusercontent.com/85092850/471007125-dd28336a-0d98-4c5c-8998-1fe20b0c9fc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQwNjA1MzAsIm5iZiI6MTc1NDA2MDIzMCwicGF0aCI6Ii84NTA5Mjg1MC80NzEwMDcxMjUtZGQyODMzNmEtMGQ5OC00YzVjLTg5OTgtMWZlMjBiMGM5ZmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODAxVDE0NTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTllOWZmOWZhNDJiZmFlZDE4MWIxMTkyMDRlZmZkODdmZTYwODg2YTBkNTBlOWJhNGIyZjkxMDQ4M2M3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-9DaiDp0kEp9it5p4HtAabFdnXxFTyqI-pWT1b1cSy8">看起来他们现在修复了？

**Comment by Zpy-ai** [comment]
ragflow的外部知识库是不行的

**Comment by baonudesifeizhai** [comment]
> ragflow的外部知识库是不行的
Got that and please replied in English

**Comment by macwx** [comment]
The latest version of dify-1.7.2 still encountered the issue of duplicate document_id and document_name in the RAGflow external knowledge base during testing
When will this issue be fixed?
