### ISSUE TITLE
Add metadata success but not work

### ISSUE THREAD

**Issue by medisean** [langgenius/dify#23080]
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Add metadata to a document in dataset.
2. Upload new document
3. Select all documents in dataset
4. Metadata -> add a value -> Save -> 【Suceess】
5. Check new document -> no metadata

### ✔️ Expected Behavior

Add metadata success and worked

### ❌ Actual Behavior

Add metadata success and not worked

**Comment by liugddx** [comment]
Has been fixed. https://github.com/langgenius/dify/pull/23000. Please use the latest version

**Comment by medisean** [comment]
Thank you

**Comment by medisean** [comment]
I

**Comment by medisean** [comment]
I check the commit still not work.  
If choose below documents both and add metadata -- Apply to all seleted documents. Add a value. Done. Success

Document 1 still has no metadata. 


- [ ] Document 1 ( no metadata )
- [ ] Document 2 (has metadata)

**Comment by medisean** [comment]
@liugddx

**Comment by liugddx** [comment]
You selected all the document update metadata and only partially succeeded?

**Comment by medisean** [comment]
NO. Document 1 alrealy has metadata( such as title), But in datasetlist, I don't know. So I choose all the documents. And add metadata(such as title) again. 

before: 
Document 1:  has metadata title:abc
Document 2: no metadata

after:
Document 1:  has metadata title:abc
Document 2: no metadata

expected:
Document 1:  has metadata title:abc
Document 2:  has metadata title:abc

**Comment by liugddx** [comment]
Can you provide some screenshots?
