### ISSUE TITLE
priority_pipeline queue is not listened and the rag_pipeline task is not excuted

### ISSUE THREAD

**Issue by Chenxiuling-Amy** [langgenius/dify#27419]
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

"priority_pipeline" not add to the entrypoint.sh and this queue is not listened after the app started。 So the knowledgebase pipeline always stuck in queue。

### ✔️ Expected Behavior

knowledgebase pipeline can be executed after summit.

### ❌ Actual Behavior

<img width="1890" height="392" alt="Image" src="https://github.com/user-attachments/assets/af32703d-6dee-4697-b858-660f1990606a" />

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/27416

**Comment by luojichen** [comment]
@crazywoola 
HI dear crazywoola:
I pulled the latest V1.9.2 (about 5 minutes ago). I noticed that PR #27416, which claims to fix the "pipeline always queuing" issue, has been merged. After checking the updated code, I can confirm that the term "priority_pipeline" was indeed added. I restarted the Docker Compose, but the issue persists.

It is worth mentioning that when I click "Test Run" in the pipeline interface of the knowledge base, it works fine. However, when uploading documents, it gets stuck at "queuing".

Could you please help me take a look at what the issue might be? Thank you!

<img width="1587" height="1075" alt="Image" src="https://github.com/user-attachments/assets/101294cf-4232-416d-a9b9-381c9867302a" />

**Comment by Chenxiuling-Amy** [comment]
I have fixed it.
Add one service in docker-compose.yaml to listen to the priority_pipeline queue.
Run `docker compose down`  to shut down all the docker containers.

Add this service to the docker-compose.yaml:

`  priority-worker:
    image: langgenius/dify-api:1.9.2
    restart: always
    environment:
      <<: *shared-api-worker-env
      # Startup mode, 'worker' starts the Celery worker for processing the queue.
      MODE: worker
      CELERY_QUEUES: priority_pipeline
      CELERY_WORKER_AMOUNT: 2  # 可选：设置并发数
      LOG_LEVEL: INFO
    # 其他必要环境变量（如 REDIS_URL、DATABASE_URL 等）
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - ./volumes/app/storage:/app/api/storage
    networks:
      - ssrf_proxy_network
      - default`
      
Run `docker compose up -d`  to start up all the docker containers.

**Comment by xuliang5114923** [comment]
I fell into the same trap too

**Comment by liuzhuosin** [comment]
> 我已经修复了它。在 docker-compose.yaml 中添加一个服务来监听priority_pipeline队列。运行以关闭所有 docker 容器。`docker compose down`
> 
> 将此服务添加到 docker-compose.yaml：
> 
> ` priority-worker: image: langgenius/dify-api:1.9.2 restart: always environment: <<: *shared-api-worker-env # Startup mode, 'worker' starts the Celery worker for processing the queue. MODE: worker CELERY_QUEUES: priority_pipeline CELERY_WORKER_AMOUNT: 2 # 可选：设置并发数 LOG_LEVEL: INFO # 其他必要环境变量（如 REDIS_URL、DATABASE_URL 等） depends_on: db: condition: service_healthy redis: condition: service_started volumes: # Mount the storage directory to the container, for storing user files. - ./volumes/app/storage:/app/api/storage networks: - ssrf_proxy_network - default`
> 
> 运行以启动所有 docker 容器。`docker compose up -d`

Thank you for sharing your method—it has helped me resolve my issue as well.

**Comment by DucDVAKB** [comment]
> I have fixed it. Add one service in docker-compose.yaml to listen to the priority_pipeline queue. Run `docker compose down` to shut down all the docker containers.
> 
> Add this service to the docker-compose.yaml:
> 
> ` priority-worker: image: langgenius/dify-api:1.9.2 restart: always environment: <<: *shared-api-worker-env # Startup mode, 'worker' starts the Celery worker for processing the queue. MODE: worker CELERY_QUEUES: priority_pipeline CELERY_WORKER_AMOUNT: 2 # 可选：设置并发数 LOG_LEVEL: INFO # 其他必要环境变量（如 REDIS_URL、DATABASE_URL 等） depends_on: db: condition: service_healthy redis: condition: service_started volumes: # Mount the storage directory to the container, for storing user files. - ./volumes/app/storage:/app/api/storage networks: - ssrf_proxy_network - default`
> 
> Run `docker compose up -d` to start up all the docker containers.

Thanks it worked, we need to add this to docker-compose.yaml urgently because i saw a lot of people are having the same error

**Comment by leike0813** [comment]
> I have fixed it. Add one service in docker-compose.yaml to listen to the priority_pipeline queue. Run `docker compose down` to shut down all the docker containers.
> 
> Add this service to the docker-compose.yaml:
> 
> ` priority-worker: image: langgenius/dify-api:1.9.2 restart: always environment: <<: *shared-api-worker-env # Startup mode, 'worker' starts the Celery worker for processing the queue. MODE: worker CELERY_QUEUES: priority_pipeline CELERY_WORKER_AMOUNT: 2 # 可选：设置并发数 LOG_LEVEL: INFO # 其他必要环境变量（如 REDIS_URL、DATABASE_URL 等） depends_on: db: condition: service_healthy redis: condition: service_started volumes: # Mount the storage directory to the container, for storing user files. - ./volumes/app/storage:/app/api/storage networks: - ssrf_proxy_network - default`
> 
> Run `docker compose up -d` to start up all the docker containers.

Thanks a lot!
It works!

**Comment by Dr-jw** [comment]
> I have fixed it. Add one service in docker-compose.yaml to listen to the priority_pipeline queue. Run `docker compose down` to shut down all the docker containers.
> 
> Add this service to the docker-compose.yaml:
> 
> ` priority-worker: image: langgenius/dify-api:1.9.2 restart: always environment: <<: *shared-api-worker-env # Startup mode, 'worker' starts the Celery worker for processing the queue. MODE: worker CELERY_QUEUES: priority_pipeline CELERY_WORKER_AMOUNT: 2 # 可选：设置并发数 LOG_LEVEL: INFO # 其他必要环境变量（如 REDIS_URL、DATABASE_URL 等） depends_on: db: condition: service_healthy redis: condition: service_started volumes: # Mount the storage directory to the container, for storing user files. - ./volumes/app/storage:/app/api/storage networks: - ssrf_proxy_network - default`
> 
> Run `docker compose up -d` to start up all the docker containers.

thx，its worked. help a lot!

**Comment by ccc81555** [comment]
邮件已收到，会尽快处理！
                                崔嘉晋

**Comment by DucDVAKB** [comment]
13/2/2026, I just tried updating to the latest version and using Dify's default Docker Compose, and this error still appears; I still have to add `priority-worker`.

**Comment by ccc81555** [comment]
邮件已收到，会尽快处理！
                                崔嘉晋
